apiVersion: v1
kind: ConfigMap
metadata:
  name: tasks-config
data:
  REST_PORT: "8082"
  LOG_LEVEL: "info"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "tasksuser"
  DB_PASSWORD: "taskspass"
  DB_NAME: "tasksdb"
  REDIS_ADDR: "redis:6379"
  RABBIT_URL: "amqp://guest:guest@rabbitmq:5672/"
  QUEUE_NAME: "task_events"
